# Spring framework configuration
spring:
  cloud:
    gateway:
      routes:
        - id: security-custom-service
          uri: lb://security-custom-service
          predicates:
            - Path=/security/custom/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-custom-service
                fallbackUri: forward:/failed/security-custom-service/redirect


# Main properties in Spring Boot to configure some general purpose services
management:
  endpoints:
    web:
      exposure:
        # Actuator endpoints exposed: actuator/routes
        include: health, info


# Swagger integration library used to centralize the documentation to every microservice.
# In local (dev profile) the URL is:
#   1. http://localhost:5555/swagger-ui/index.html to display the UI with all defined endpoints
springdoc:
  documentation:
    # Custom property to include the documented microservices using Swagger
    documentedServices: security-custom-service
    # Custom property to include the path of the OpenAPI documentation in Json format of the documented microservices
    microservicesPath: /api-docs
  swagger-ui:
    # To disable the swagger-ui default petstore url
    disable-swagger-default-url: true
    # Swagger-ui will be accessible from the application root path directly
    use-root-path: true