# Spring framework configuration
spring:
  cloud:
    gateway:
      routes:
        - id: security-custom-service
          uri: lb://security-custom-service
          predicates:
            - Path=/security/custom/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-custom-service
                fallbackUri: forward:/failed/security-custom-service/redirect
        - id: security-oauth-service
          uri: lb://security-oauth-service
          predicates:
            - Path=/security/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-oauth-service
                fallbackUri: forward:/failed/security-oauth-service/redirect


# Custom properties to manage how the internal filter should manage the data to include in the logs
log:
  endpoints:
    body:
      # Comma-separated HTTP methods to include the request body in logs
      httpMethods: PATCH,POST,PUT
      # Comma-separated URLs (without: protocol, domain and port) whose body will not be added to the logs (mainly to avoid exposing sensitive data)
      pathToAvoidLogBody: /security/custom/authentication/login,/security/custom/authentication/login/token


# Main properties in Spring Boot to configure some general purpose services
management:
  endpoints:
    web:
      exposure:
        # Actuator endpoints exposed: actuator/routes
        include: health, info
  tracing:
    sampling:
      # To log traceId and spanId in every request
      probability: 1.0


# Swagger integration library used to centralize the documentation to every microservice.
# In local (dev profile) the URL is:
#   1. http://localhost:5555/swagger-ui/index.html to display the UI with all defined endpoints
springdoc:
  documentation:
    # Custom property to include the documented microservices using Swagger
    documentedServices: security-custom-service,security-oauth-service
    # Custom property to include the path of the OpenAPI documentation in JSON format of the documented microservices
    microservicesPath: /api-docs
  swagger-ui:
    # To disable the swagger-ui default petstore url
    disable-swagger-default-url: true
    # Swagger-ui will be accessible from the application root path directly
    use-root-path: true